#include <string>

std::string exampleDesktopCpuInfo(
  "processor   : 0\n"
  "vendor_id   : GenuineIntel\n"
  "cpu family  : 6\n"
  "model       : 37\n"
  "model name  : Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz\n"
  "stepping    : 2\n"
  "cpu MHz     : 933.000\n"
  "cache size  : 3072 KB\n"
  "physical id : 0\n"
  "siblings    : 4\n"
  "core id     : 0\n"
  "cpu cores   : 2\n"
  "apicid      : 0\n"
  "initial apicid  : 0\n"
  "fdiv_bug    : no\n"
  "hlt_bug     : no\n"
  "f00f_bug    : no\n"
  "coma_bug    : no\n"
  "fpu     : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level : 11\n"
  "wp      : yes\n"
  "flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dts tpr_shadow vnmi flexpriority ept vpid\n"
  "bogomips    : 4256.49\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor   : 1\n"
  "vendor_id   : GenuineIntel\n"
  "cpu family  : 6\n"
  "model       : 37\n"
  "model name  : Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz\n"
  "stepping    : 2\n"
  "cpu MHz     : 933.000\n"
  "cache size  : 3072 KB\n"
  "physical id : 0\n"
  "siblings    : 4\n"
  "core id     : 0\n"
  "cpu cores   : 2\n"
  "apicid      : 1\n"
  "initial apicid  : 1\n"
  "fdiv_bug    : no\n"
  "hlt_bug     : no\n"
  "f00f_bug    : no\n"
  "coma_bug    : no\n"
  "fpu     : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level : 11\n"
  "wp      : yes\n"
  "flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dts tpr_shadow vnmi flexpriority ept vpid\n"
  "bogomips    : 4256.40\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor   : 2\n"
  "vendor_id   : GenuineIntel\n"
  "cpu family  : 6\n"
  "model       : 37\n"
  "model name  : Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz\n"
  "stepping    : 2\n"
  "cpu MHz     : 933.000\n"
  "cache size  : 3072 KB\n"
  "physical id : 0\n"
  "siblings    : 4\n"
  "core id     : 2\n"
  "cpu cores   : 2\n"
  "apicid      : 4\n"
  "initial apicid  : 4\n"
  "fdiv_bug    : no\n"
  "hlt_bug     : no\n"
  "f00f_bug    : no\n"
  "coma_bug    : no\n"
  "fpu     : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level : 11\n"
  "wp      : yes\n"
  "flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dts tpr_shadow vnmi flexpriority ept vpid\n"
  "bogomips    : 4256.43\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor   : 3\n"
  "vendor_id   : GenuineIntel\n"
  "cpu family  : 6\n"
  "model       : 37\n"
  "model name  : Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz\n"
  "stepping    : 2\n"
  "cpu MHz     : 933.000\n"
  "cache size  : 3072 KB\n"
  "physical id : 0\n"
  "siblings    : 4\n"
  "core id     : 2\n"
  "cpu cores   : 2\n"
  "apicid      : 5\n"
  "initial apicid  : 5\n"
  "fdiv_bug    : no\n"
  "hlt_bug     : no\n"
  "f00f_bug    : no\n"
  "coma_bug    : no\n"
  "fpu     : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level : 11\n"
  "wp      : yes\n"
  "flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm arat dts tpr_shadow vnmi flexpriority ept vpid\n"
  "bogomips    : 4256.42\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
);

std::string exampleServerCpuInfo(
  "processor       : 0\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 0\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 1\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 1\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 2\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 2\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 3\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 3\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 4\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 4\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 5\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 5\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 6\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 6\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 7\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 7\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 8\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 8\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 9\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 9\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 10\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 10\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 11\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 11\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 12\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 12\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 13\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 13\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 14\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 14\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 15\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 0\n"
  "siblings        : 16\n"
  "core id         : 15\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 16\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 0\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 17\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 1\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 18\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 2\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 19\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 3\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 20\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 4\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 21\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 5\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 22\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 6\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 23\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 7\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 24\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 8\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 25\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 9\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 26\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 10\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 27\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 11\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 28\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 12\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 29\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 13\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 30\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 14\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
  "\n"
  "processor       : 31\n"
  "vendor_id       : GenuineIntel\n"
  "cpu family      : 6\n"
  "model           : 79\n"
  "model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz\n"
  "stepping        : 1\n"
  "microcode       : 0xffffffff\n"
  "cpu MHz         : 2601.000\n"
  "cache size      : 256 KB\n"
  "physical id     : 1\n"
  "siblings        : 16\n"
  "core id         : 15\n"
  "cpu cores       : 16\n"
  "apicid          : 0\n"
  "initial apicid  : 0\n"
  "fpu             : yes\n"
  "fpu_exception   : yes\n"
  "cpuid level     : 6\n"
  "wp              : yes\n"
  "flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt ibrs ibpb stibp ssbd\n"
  "bogomips        : 5202.00\n"
  "clflush size    : 64\n"
  "cache_alignment : 64\n"
  "address sizes   : 36 bits physical, 48 bits virtual\n"
  "power management:\n"
);

